shared:
    image: node:8

jobs:
    main:
        requires: [~pr, ~commit]
        environment:
            SD_SONAR_OPTS: "-Dsonar.sources=index.js -Dsonar.language=js"
        steps:
            - meta: meta set meta.summary.coverage "99"
