shared:
    image: nonsense
    
jobs:
    main:
        requires: [~pr, ~commit]
        steps:
        - meta: |
            meta set meta.summary.coverage "Coverage increased by 90%"
            meta set meta.summary.markdown "this markdown comment is **bold** and *italic* meow"
